version: "3.0"
services:
  app:
    image: __IMAGE_NAME__
    ports:
      - 8080:8080
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/github-test
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs

#ecs-cli compose --region ap-northeast-1 --file docker-compose.yml --ecs-params ecs-params.yml up --launch-type FARGATE